// Single source of truth for the site's public identity (SEO, manifest,
// emails). Server-only — every importer is a server component, so plain
// (non-NEXT_PUBLIC) Vercel variables are readable here.

// The origin every canonical URL, Open Graph tag and sitemap entry is built
// from. Getting this wrong is not cosmetic: a canonical pointing at a domain
// we do not serve hands our pages' ranking to that domain, and an og:image
// there 404s, so shared links render with no card. Hence: never guess a
// hard-coded domain — fall back to the one Vercel tells us we are serving.
function resolveSiteUrl(): string {
  // 1. Explicit override — set this once a custom domain is attached.
  const explicit = process.env.NEXT_PUBLIC_SITE_URL;
  if (explicit) return explicit.replace(/\/$/, "");
  // 2. The project's stable production domain, injected by Vercel. (Not
  //    VERCEL_URL: that one is per-deployment and changes on every push,
  //    which would make canonical URLs churn.)
  const production = process.env.VERCEL_PROJECT_PRODUCTION_URL;
  if (production) return `https://${production}`;
  // 3. Local dev.
  return "http://localhost:3000";
}

export const SITE_URL = resolveSiteUrl();

export const SITE_NAME = "welock.in";

export const SITE_TITLE = "welock.in — Lock in. Study together.";

export const SITE_DESCRIPTION =
  "Free video study rooms with a shared focus timer. Lock in with your crew " +
  "in a private room, or join live public rooms started by verified " +
  "university students.";

// The social card, generated by app/opengraph-image.tsx. Declared explicitly
// rather than left to the file convention: that convention only auto-attaches
// the image to its own route segment, so a nested route (a room) that sets its
// own openGraph would otherwise render a card with no image.
export const OG_IMAGE = {
  url: "/opengraph-image",
  width: 1200,
  height: 630,
  alt: SITE_DESCRIPTION,
};

// Shared Open Graph fields. Next merges metadata shallowly — a route that
// sets `openGraph` REPLACES the parent's wholesale — so every route that adds
// its own og:url spreads this to keep the card intact.
export const OG_BASE = {
  type: "website" as const,
  siteName: SITE_NAME,
  title: SITE_TITLE,
  description: SITE_DESCRIPTION,
  images: [OG_IMAGE],
};
