// Single source of truth for the site's public identity (SEO, manifest,
// emails). NEXT_PUBLIC_SITE_URL overrides the canonical origin in
// non-production deployments (previews, staging).

export const SITE_URL = (
  process.env.NEXT_PUBLIC_SITE_URL || "https://welock.in"
).replace(/\/$/, "");

export const SITE_NAME = "welock.in";

export const SITE_TITLE = "welock.in — Lock in. Study together.";

export const SITE_DESCRIPTION =
  "Free video study rooms with a shared focus timer. Lock in with your crew " +
  "in a private room, or join live public rooms started by verified " +
  "university students.";

// The social card, generated by app/opengraph-image.tsx. Declared explicitly
// rather than left to the file convention: that convention only auto-attaches
// the image to its own route segment, so a nested route (a room) that sets its
// own openGraph would otherwise render a card with no image.
export const OG_IMAGE = {
  url: "/opengraph-image",
  width: 1200,
  height: 630,
  alt: SITE_DESCRIPTION,
};

// Shared Open Graph fields. Next merges metadata shallowly — a route that
// sets `openGraph` REPLACES the parent's wholesale — so every route that adds
// its own og:url spreads this to keep the card intact.
export const OG_BASE = {
  type: "website" as const,
  siteName: SITE_NAME,
  title: SITE_TITLE,
  description: SITE_DESCRIPTION,
  images: [OG_IMAGE],
};
